# -*- coding: utf-8 -*-
"""AnalyzeDailyWeatherData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iRG_LJ1Sr1zK2MpGFk-5-Bls__pSvfyn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Loading The dataset
Data = pd.read_csv('/content/weatherHistory.csv')
Data.head()

Data.describe()

Data = Data.drop(['Daily Summary','Wind Bearing (degrees)','Summary','Precip Type','Temperature (C)','Loud Cover','Visibility (km)','Pressure (millibars)'],axis=1)

Data.head()

Data['Formatted Date'] = pd.to_datetime(Data['Formatted Date'],utc=True)
Data =Data.set_index('Formatted Date')
ds = Data[['Apparent Temperature (C)','Humidity','Wind Speed (km/h)']].resample('MS').mean()
ds

plt.figure(figsize=(15,3));
plt.plot(ds['Humidity'], label = 'Humidity', color ='blue',linestyle='dashed');
plt.plot(ds['Apparent Temperature (C)'], label = 'Apparent temp.', color  = 'orange');
plt.title('Variation of Apparent temperature v/s Humidity', fontsize = 25);
plt.legend(loc=0, fontsize =12);
plt.xticks(fontsize = 15);
plt.yticks(fontsize=13);

plt.figure(figsize=(15,3));
plt.plot(ds['Wind Speed (km/h)'], label = 'Wind Speed (km/h)', color ='red',linestyle='dotted');
plt.plot(ds['Apparent Temperature (C)'], label = 'Apparent temp.', color  = 'orange');
plt.title('Variation of Apparent temperature v/s Wind Speed (km/h)', fontsize = 25);
plt.legend(loc=0, fontsize =12);
plt.xticks(fontsize = 15);
plt.yticks(fontsize=13);

plt.figure(figsize=(15,3));
plt.plot(ds['Wind Speed (km/h)'], label = 'Wind Speed (km/h)', color ='red',linestyle='dotted');
plt.plot(ds['Humidity'], label = 'Humidity.', color  = 'blue', linestyle='dashed');
plt.title('Variation of Wind Speed (km/h) v/s Humidity', fontsize = 25);
plt.legend(loc=0, fontsize =12);
plt.xticks(fontsize = 15);
plt.yticks(fontsize=13);

may =  ds[ds.index.month==5]
plt.figure(figsize=(15,3))
plt.plot(may.loc['2006-05-01':'2016-05-01','Apparent Temperature (C)'],marker='o', label = 'Apparent Temperature', color ='green',linestyle='-');
plt.plot(may.loc['2006-05-01':'2016-05-01','Humidity'], marker='o',label = 'Humidity', color  = 'orange');
plt.legend(loc='center right', fontsize =15);
plt.xlabel('Month of May',fontsize = 15);
plt.title('Humidity v/s Apparent Temperature', fontsize = 15);

may =  ds[ds.index.month==5]
plt.figure(figsize=(15,3))
plt.plot(may.loc['2006-05-01':'2016-05-01','Wind Speed (km/h)'],marker='o', label = 'Wind Speed (km/h)', color ='red',linestyle='dotted');
plt.plot(may.loc['2006-05-01':'2016-05-01','Humidity'], marker='o',label = 'Humidity', color  = 'orange', linestyle='-');
plt.legend(loc='center right', fontsize =15);
plt.xlabel('Month of May',fontsize = 15);
plt.title('Wind Speed (km/h) v/s Humidity', fontsize = 15);

may =  ds[ds.index.month==5]
plt.figure(figsize=(15,3))
plt.plot(may.loc['2006-05-01':'2016-05-01','Apparent Temperature (C)'], marker='o',label = 'Humidity', color  = 'green');
plt.plot(may.loc['2006-05-01':'2016-05-01','Wind Speed (km/h)'],marker='o', label = 'Wind Speed (km/h)', color ='red',linestyle='dotted');
plt.legend(loc='center right', fontsize =15);
plt.xlabel('Month of May',fontsize = 15);
plt.title('Wind Speed (km/h) v/s Apparent Temperature', fontsize = 15);

