# -*- coding: utf-8 -*-
"""Slashmark Basic-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/151VxLVEOYqSzvITf9NayTRb-6DS9tqdF
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline

tasks = pd.read_csv('/content/tasks.csv')

def save_tasks(data):
  data.to_csv('tasks.csv', index=False)

x=tasks['description']
y=tasks['priority']

vectorizer = CountVectorizer()
clf = MultinomialNB()
model = make_pipeline(vectorizer, clf)
model.fit(x,y)

def add_task(description, priority):
  tasks=pd.read_csv('/content/tasks.csv')
  modified_task = pd.DataFrame({'description': [description], 'priority': [priority]})
  tasks = pd.concat([tasks, modified_task], ignore_index=True)
  save_tasks(tasks)

def delete_task(description):
  tasks = pd.read_csv('/content/tasks.csv')
  n_tasks = tasks[tasks['description'] != description]
  save_tasks(n_tasks)

def list_tasks():
  tasks=pd.read_csv('/content/tasks.csv')
  if tasks.empty:
    print("No tasks available.")
  else:
    print(tasks)

def recommend_task():
  tasks=pd.read_csv("/content/tasks.csv")
  if tasks.empty:
    print("NO tasks")
  else:
    high_priority_tasks=tasks[tasks['priority'] == 'High']
    if high_priority_tasks.empty:
      print('Null high priority')
    else:
      print(high_priority_tasks['description'][0])

while True:
  print("\nTask Management App")
  print("1. Add Task")
  print("2. Remove Task")
  print("3. List Tasks")
  print("4. Recommend Task")
  print("5. Exit")

  choice = input("Select an option: ")
  if choice == "1":
    description = input("Enter task description: ")
    priority = input("Enter task priority (Low/Medium/High): ").capitalize()
    add_task(description, priority)
    print("Task added successfully.")

  elif choice == "2":
    description = input("Enter task description to remove: ")
    delete_task(description)
    print("Task removed successfully.")

  elif choice == "3":
    list_tasks()

  elif choice == "4":
    recommend_task()

  elif choice == "5":
    print("Thankyou")
    break

  else:
    print("Wrong Input")